app:
  pdl:
    behandlingsnummer: B986
  utbetaling:
    #    TODO Sette rett navn p√• topic
    utbetaling-topic: historisk.utbetaling.v1
    status-topic: helved.status.v1

spring:
  application:
    name: superhelt
  http:
    client:
      connect-timeout: 1s
      read-timeout: 3s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
  web:
    resources:
      static-locations:
        - classpath:/static

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: tx-

    consumer:
      group-id: ${spring.application.name}
  cache:
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=20m
    cache-names: pdlCache,tilgangsmaskinCache

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

