spring:
  application:
    name: super
  http:
    client:
      connect-timeout: 1s
      read-timeout: 3s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
#          audiences: ${AZURE_APP_CLIENT_ID}
  web:
    resources:
      static-locations:
        - classpath:/static

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SSL
    ssl:
      key-store-location: ${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      trust-store-location: ${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}

app:
  pdl:
    behandlingsnummer: B986
