app:
  pdl:
    behandlingsnummer: B986
  utbetaling:
    utbetaling-topic: superhelt.utbetaling.test
    status-topic: helved.status.v1

spring:
  application:
    name: super
  http:
    client:
      connect-timeout: 1s
      read-timeout: 3s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
  #          audiences: ${AZURE_APP_CLIENT_ID}
  web:
    resources:
      static-locations:
        - classpath:/static

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

