name: Build and Test reusable workflow
on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
        description: 'Token with read access to the repository'
    outputs:
      image:
        description: 'Docker image '
        value: ${{ jobs.build.outputs.image }}
      telemetry:
        description: 'Telemetry data'
        value: ${{ jobs.build.outputs.telemetry }}

jobs:
  build:
    name: "Bygg backend"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
          registry-url: "https://npm.pkg.github.com"

      - name: Installere node moduler
        working-directory: ./frontend
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build artifacts
        run: mvn --batch-mode verify
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run tests
        run: mvn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: historisk
          docker_context: ./backend
