name: Create or update Kafka topics

on:
  push:
    #    branches:
    #      - main
    paths:
      - '.nais/app/topics.yaml'
      - '.github/workflows/kafka.yml'

jobs:
  create-kafka-topics-dev:
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/dev.json
